jobs:
- job: libzmq_windows
  strategy:
    matrix:
      x86:
        msBuildPlatform: Win32
      x64:
        msBuildPlatform: x64
  pool:
    vmImage: vs2017-win2016
  steps:
  - powershell: DotZeroMQ/download_lib.ps1
    displayName: Download libzmq sources
  
  - task: VSBuild@1
    displayName: Build libzmq
    inputs:
      solution: DotZeroMQ\zeromq\builds\msvc\vs2015\libzmq\libzmq.vcxproj
      vsVersion: 15.0
      platform: $(msBuildPlatform)
      configuration: ReleaseDLL
      maximumCpuCount: true
      msbuildArchitecture: x64
      createLogFile: true

  - script: cp DotZeroMQ/zeromq/bin/$(msBuildPlatform)/Release/v140/dynamic/libzmq.dll $(Build.ArtifactStagingDirectory)/libzmq-$(msBuildPlatform).dll
    displayName: 'Copy libzmq to artifacts directory'

  - upload: $(Build.ArtifactStagingDirectory)
    displayName: Publish libzmq
    artifact: libzmq-$(msBuildPlatform).dll
