variables:
  buildConfiguration: Release
  libzmqVersion: 4.3.2

trigger:
- master

stages:
- stage: libzmq_native
  displayName: Build libzmq Native Libraries
  jobs:
  - template: libzmq_nix.yml
  - template: libzmq_win.yml

- template: build.yml
- template: publish.yml