variables:
  buildConfiguration: 'Release'

trigger:
- master

stages:
- stage: libzmq_native
  displayName: Build libzmq Native Libraries
  jobs:
  - template: libzmq_linux.yml
  - template: libzmq_osx.yml
  - template: libzmq_windows.yml

- template: build.yml
- template: publish.yml