stages:
- stage: Publish
  dependsOn: build
  condition: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))"
  jobs:
  - job:
    pool:
      vmImage: windows-latest
    steps:
    - download: current
      artifact: package
      displayName: Download NuGet package Artifact

    - task: NuGetCommand@2
      displayName: Push to NuGet
      inputs:
        command: push
        packagesToPush: $(Pipeline.Workspace)/package/*.nupkg
        nuGetFeedType: external
        publishFeedCredentials: NuGet.org
